# Generated by Django 2.2.6 on 2019-10-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('height', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.PositiveIntegerField(db_index=True, unique=True)),
                ('hash', models.CharField(max_length=66, unique=True)),
            ],
        ),
    ]
